name: booksly
description: Booksly help you to manage your ebook library with opds catalogs.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  archive: ^3.3.6
  auto_route: ^5.0.4
  bloc: ^8.1.0
  cupertino_icons: ^1.0.5
  dio: ^5.0.1
  easy_localization: ^3.0.1
  equatable: ^2.0.5
  file_picker: ^5.2.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  injectable: ^2.1.0
  intl: ^0.17.0
  macos_ui: ^1.10.0
  xml: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  injectable_generator: ^2.1.3
  hive_generator: ^2.0.0
  auto_route_generator: ^5.0.3
  freezed: ^2.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
