name: settings
description: Settings module.
version: 1.0.0
publish_to: 'none'
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.6

# Add regular dependencies here.
dependencies:
  common:
    path: '../common'
  dio: ^5.3.0
  get_it: ^7.6.0
  hive: ^2.2.3
  injectable: ^2.1.2
  path_provider: ^2.0.15
  translit: ^2.0.1
  xml: ^6.3.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.0
  injectable_generator: ^2.1.6
