name: booksly
description: Booksly help you to manage your ebook library with opds catalogs.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  common:
    path: '../packages/common'
  download_manager:
    path: '../packages/download_manager'
  local_library:
    path: '../packages/local_library'
  opds_catalog:
    path: '../packages/opds_catalog'
  settings:
    path: '../packages/settings'
  archive: ^3.3.6
  auto_route: ^7.6.0
  bloc: ^8.1.0
  cupertino_icons: ^1.0.5
  dio: ^5.2.1+1
  easy_localization: ^3.0.2
  equatable: ^2.0.5
  file_picker: ^5.2.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  injectable: ^2.1.0
  intl: ^0.18.0
  path_provider: ^2.0.15
  translit: ^2.0.1
  xml: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  injectable_generator: ^2.1.3
  hive_generator: ^2.0.0
  auto_route_generator: ^7.1.1
  freezed: ^2.3.2
  test: ^1.24.1

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
